// Mapa de país (nombre) → código ISO, y de ahí sacamos la bandera emoji
const COUNTRY_CODES: Record<string, string> = {
  'argentina': 'AR',
  'uruguay': 'UY',
  'chile': 'CL',
  'paraguay': 'PY',
  'bolivia': 'BO',
  'peru': 'PE',
  'perú': 'PE',
  'colombia': 'CO',
  'ecuador': 'EC',
  'venezuela': 'VE',
  'brasil': 'BR',
  'brazil': 'BR',
  'mexico': 'MX',
  'méxico': 'MX',
  'españa': 'ES',
  'espana': 'ES',
  'spain': 'ES',
  'estados unidos': 'US',
  'united states': 'US',
  'usa': 'US',
  'panamá': 'PA',
  'panama': 'PA',
  'costa rica': 'CR',
  'guatemala': 'GT',
  'honduras': 'HN',
  'el salvador': 'SV',
  'nicaragua': 'NI',
  'república dominicana': 'DO',
  'republica dominicana': 'DO',
  'puerto rico': 'PR',
  'cuba': 'CU',
  // Europa
  'francia': 'FR',
  'france': 'FR',
  'italia': 'IT',
  'italy': 'IT',
  'alemania': 'DE',
  'germany': 'DE',
  'reino unido': 'GB',
  'united kingdom': 'GB',
  'inglaterra': 'GB',
  'gran bretaña': 'GB',
  'portugal': 'PT',
  'países bajos': 'NL',
  'paises bajos': 'NL',
  'holanda': 'NL',
  'bélgica': 'BE',
  'belgica': 'BE',
  'suiza': 'CH',
  'austria': 'AT',
  'irlanda': 'IE',
  'suecia': 'SE',
  'noruega': 'NO',
  'dinamarca': 'DK',
  'finlandia': 'FI',
  'polonia': 'PL',
  'grecia': 'GR',
  'república checa': 'CZ',
  'republica checa': 'CZ',
  'chequia': 'CZ',
  'hungría': 'HU',
  'hungria': 'HU',
  'rumanía': 'RO',
  'rumania': 'RO',
  'bulgaria': 'BG',
  'croacia': 'HR',
  'serbia': 'RS',
  'rusia': 'RU',
  'ucrania': 'UA',
  'turquía': 'TR',
  'turquia': 'TR',
  'luxemburgo': 'LU',
  'islandia': 'IS',
  'eslovaquia': 'SK',
  'eslovenia': 'SI',
  'estonia': 'EE',
  'letonia': 'LV',
  'lituania': 'LT',
  'malta': 'MT',
  'chipre': 'CY',
  'mónaco': 'MC',
  'monaco': 'MC',
  'andorra': 'AD',
}

export function countryCode(name?: string | null): string {
    if (!name) return ''
    return (COUNTRY_CODES[name.trim().toLowerCase()] ?? '').toLowerCase()
  }